#!/usr/bin/env node
/**
 * Build a 2026 race catalog from ironman.com and emit src/races.generated.js
 *
 * Strategy:
 * - Pull ironman.com sitemap(s)
 * - Collect candidate race detail pages under /races/im* and /races/im703*
 * - For each page, fetch HTML and extract:
 *   - name
 *   - date (must include 2026)
 *   - location (country/locality/region)
 * - Normalize to our dynamics enums.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT = 'https://www.ironman.com';

const DYNAMICS = {
  swimCurrent: ['none', 'mild', 'strong'],
  bikeTerrain: ['flat', 'rolling', 'hilly'],
  runTerrain: ['flat', 'rolling', 'hilly'],
  heat: ['cool', 'warm', 'hot'],
};

const defaultDistances = {
  '140.6': { swimYards: 4224, bikeMiles: 112, runMiles: 26.2 },
  '70.3': { swimYards: 2112, bikeMiles: 56, runMiles: 13.1 },
};

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 80);
}

async function fetchText(url, { timeoutMs = 15000 } = {}) {
  const ac = new AbortController();
  const t = setTimeout(() => ac.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      signal: ac.signal,
      headers: {
        'user-agent': 'clawdbot-race-catalog/0.1 (educational)',
        accept: 'text/html,application/xml;q=0.9,*/*;q=0.8',
      },
    });
    if (!res.ok) throw new Error(`Fetch failed ${res.status} for ${url}`);
    return await res.text();
  } finally {
    clearTimeout(t);
  }
}

async function fetchXml(url) {
  return await fetchText(url);
}

function extractSitemapUrls(xml) {
  const urls = [];
  // <loc>https://...</loc>
  const re = /<loc>([^<]+)<\/loc>/g;
  let m;
  while ((m = re.exec(xml))) urls.push(m[1]);
  return urls;
}

function looksLikeRacePage(url) {
  // Keep only canonical race detail pages (no extra path segments)
  // Examples:
  // - https://www.ironman.com/races/im703-maine
  // - https://www.ironman.com/races/im-maryland
  if (!url.startsWith(`${ROOT}/races/`)) return false;
  if (url.endsWith('/register')) return false;
  if (!/\/races\/(im703-[a-z0-9-]+|im-[a-z0-9-]+)$/.test(url)) return false;
  return true;
}

const COURSE_OVERRIDES = {
  // Source: ironman.com course overview page (bike elevation gain)
  // https://www.ironman.com/races/im-chattanooga/course
  'im-chattanooga': { bikeElevationGainFt: 4300 },
};

function parseRaceFromHtml({ url, html }) {
  const m = html.match(/<script[^>]+application\/ld\+json[^>]*>([\s\S]*?)<\/script>/i);
  if (!m) return null;

  let data;
  try {
    data = JSON.parse(m[1]);
  } catch {
    return null;
  }

  const graph = data?.['@graph'];
  const ev = Array.isArray(graph) ? graph.find((x) => x?.['@type'] === 'SportsEvent') : null;
  if (!ev?.name || !ev?.startDate) return null;

  const year = String(ev.startDate).slice(0, 4);
  if (year !== '2026') return null;

  const name = String(ev.name).trim();

  // Prefer stable ids based on the canonical race URL slug.
  const urlSlug = new URL(url).pathname.split('/').filter(Boolean).pop();
  if (!urlSlug) return null;

  const distance = urlSlug.startsWith('im703-') || /70\.3/.test(name) ? '70.3' : '140.6';
  const courseOverride = COURSE_OVERRIDES[urlSlug] ?? null;

  const desc = String(ev.description ?? '').toLowerCase();

  // Heuristic dynamics from description (v1)
  const swimCurrent = (() => {
    if (/(downriver|downstream|swift|fastest|current-assisted)/.test(desc)) return 'strong';
    if (/river/.test(desc)) return 'mild';
    return 'none';
  })();

  const terrainFromDesc = (kind) => {
    // kind: 'bike'|'run'
    const window = desc;
    // Try explicit keywords first
    if (/\bflat\b/.test(window)) return 'flat';
    if (/\brolling\b/.test(window)) return 'rolling';
    if (/\bhilly\b/.test(window)) return 'hilly';
    // Common adjectives
    if (/challenging/.test(window) || /climb/.test(window) || /elevation/.test(window)) return 'hilly';
    return 'rolling';
  };

  const bikeTerrain = terrainFromDesc('bike');
  const runTerrain = /\bflat\b/.test(desc) ? 'flat' : /\brolling\b/.test(desc) ? 'rolling' : /\bhilly\b/.test(desc) ? 'hilly' : 'rolling';

  // Heat: rough by month in US
  const month = Number(String(ev.startDate).slice(5, 7));
  const heat = month >= 6 && month <= 9 ? 'warm' : 'cool';

  const locality = ev?.location?.address?.addressLocality;
  const region = ev?.location?.address?.addressRegion;
  const country = ev?.location?.address?.addressCountry;

  const parts = [locality, region, country].map((x) => String(x ?? '').trim()).filter(Boolean);

  return {
    id: urlSlug,
    brand: 'IRONMAN',
    name,
    distance,
    ...defaultDistances[distance],
    ...(courseOverride ?? {}),
    date: String(ev.startDate),
    location: parts.join(', '),
    dynamics: { swimCurrent, bikeTerrain, runTerrain, heat },
    sourceUrl: url,
  };
}

function toGeneratedJs(races) {
  const header = `// AUTO-GENERATED by scripts/buildRaceCatalog.mjs\n// Source: ironman.com race pages\n// Worldwide, 2026\n\n`;
  const body = `export const RACE_CATALOG = ${JSON.stringify(races, null, 2)};\n\nexport function getRaceById(id) {\n  return RACE_CATALOG.find((r) => r.id === id) ?? null;\n}\n`;
  return header + body;
}

async function main() {
  const sitemapIndexUrl = `${ROOT}/sitemap.xml`;
  const xml = await fetchXml(sitemapIndexUrl);
  let sitemapUrls = extractSitemapUrls(xml);

  // sitemap.xml might be a sitemap index, or a urlset.
  // If it's urlset, just treat those as urls.
  const isIndex = xml.includes('<sitemapindex');

  let candidateUrls = [];
  if (isIndex) {
    // filter to sitemaps that likely contain race pages
    sitemapUrls = sitemapUrls.filter((u) => u.includes('sitemap'));
    for (const sm of sitemapUrls) {
      try {
        const smXml = await fetchXml(sm);
        const urls = extractSitemapUrls(smXml).filter(looksLikeRacePage);
        candidateUrls.push(...urls);
      } catch {
        // ignore
      }
    }
  } else {
    candidateUrls = sitemapUrls.filter(looksLikeRacePage);
  }

  candidateUrls = Array.from(new Set(candidateUrls));

  const races = [];

  // Small concurrency to avoid being rude to ironman.com
  const concurrency = 6;
  let i = 0;
  let processed = 0;
  async function worker() {
    while (i < candidateUrls.length) {
      const idx = i++;
      const url = candidateUrls[idx];
      try {
        const html = await fetchText(url, { timeoutMs: 10000 });
      // Cheap text extraction: strip tags
      const race = parseRaceFromHtml({ url, html });
      processed++;
      if (processed % 25 === 0) {
        console.log(`Processed ${processed}/${candidateUrls.length}… found ${races.length}`);
      }
      if (!race) continue;

      // sanity
      if (!DYNAMICS.bikeTerrain.includes(race.dynamics.bikeTerrain)) race.dynamics.bikeTerrain = 'rolling';
      if (!DYNAMICS.runTerrain.includes(race.dynamics.runTerrain)) race.dynamics.runTerrain = 'rolling';
      if (!DYNAMICS.swimCurrent.includes(race.dynamics.swimCurrent)) race.dynamics.swimCurrent = 'none';

        races.push(race);
      } catch {
        // ignore
      }
    }
  }

  await Promise.all(Array.from({ length: concurrency }, () => worker()));

  // Sort by distance, then name
  races.sort((a, b) => (a.distance === b.distance ? a.name.localeCompare(b.name) : b.distance.localeCompare(a.distance)));

  const outPath = path.resolve(process.cwd(), 'src', 'races.generated.js');
  await fs.writeFile(outPath, toGeneratedJs(races), 'utf8');

  // Print summary
  console.log(`Generated ${races.length} races -> ${outPath}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
